spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itsm?characterEncoding=UTF-8
    username: root
    password: 123589
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: Guest123

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sungcor.baobiao.entity

